version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Populate secure.properties
          command: |
            echo "MAPS_API_KEY=\"$MAPS_API_KEY\"" > ~/project/secure.properties
            echo "PLACES_API_KEY=\"$PLACES_API_KEY\"" >> ~/project/secure.properties
      - run:
          name: Store google-services.json
          command: echo $GCLOUD_SERVICES_JSON > ${HOME}/project/app/google-services.json
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --device model=Pixel2,version=28,locale=en,orientation=portrait \
              --device model=hwALE-H,version=21,locale=en,orientation=portrait \
              --device model=flame,version=29,locale=en,orientation=portrait \
              --app ~/project/app/build/outputs/apk/debug/app-debug.apk \
              --test ~/project/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            sudo gsutil -m cp -r -U `sudo gsutil ls gs://cloud-test-${GOOGLE_PROJECT_ID} | tail -1` ${CIRCLE_ARTIFACTS}/ | true

      - store_test_results:
          path: test-results
